// src/components/input/SFileInputBtn.vue
<template>
  <div class="s-file-input">
    <v-file-input ref="importFile" :model-value="file" class="d-none" @update:model-value="handleChange" :accept="accept"/>
    <v-text-field
      :model-value="fileName"
      variant="outlined"
      density="compact"
      :hide-details="hideDetails"
      readonly
      :error-messages="errorMessages"
      :placeholder="placeholder"
    />
    <SBtn height="30" variant="outlined" :disabled="btnDisabled" @click="$refs.importFile.click()">
      <SIcon name="file" :size="16" class="mr-1" />
      {{buttonText}}
    </SBtn>
  </div>
</template>

<script setup>
import { SBtn, SIcon } from '@';
import { ref, onMounted } from 'vue'
const props = defineProps({
  placeholder: {
    type: String,
    default: '파일을 선택하세요',
  },
  modelValue: {
    type: [Object, String],
    default: null,
  },
  errorMessages: {
    type: Array,
    default: () => [],
  },
  btnDisabled: {
    type: Boolean,
    default: false,
  },
  hideDetails: {
    type: [String, Boolean],
    default: 'auto',
  },
  buttonText: {
    type: String,
    default: '파일 찾기',
  },
  accept: {
    type: String,
    default: '*',
  }
})

const emits = defineEmits(['update:model-value'])

const file = ref(null)
const fileName = ref(null)

const handleChange = value => {
  file.value = value
  fileName.value = value?.name
  emits('update:model-value', value)
}

onMounted(() => {
  file.value = props.modelValue
})
</script>
<style lang="scss">
.s-file-input {
  display: flex;
  align-items: center;
  gap: 10px;
}
</style>

// src/components/Input/SFileInputBtn.tsx
import React, { useRef, useState, useEffect } from 'react';
import { SBtn } from '../button/SBtn';
import { SIcon } from '../images/SIcon';
import './SFileInputBtn.scss';

interface SFileInputBtnProps {
  placeholder?: string;
  modelValue?: File | string | null;
  errorMessages?: string[];
  btnDisabled?: boolean;
  hideDetails?: string | boolean;
  buttonText?: string;
  accept?: string;
  onUpdateModelValue?: (value: File | null) => void;
}

export const SFileInputBtn: React.FC<SFileInputBtnProps> = ({
  placeholder = '파일을 선택하세요',
  modelValue = null,
  errorMessages = [],
  btnDisabled = false,
  hideDetails = 'auto',
  buttonText = '파일 찾기',
  accept = '*',
  onUpdateModelValue,
}) => {
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [file, setFile] = useState<File | null>(null);
  const [fileName, setFileName] = useState<string | null>(null);

  useEffect(() => {
    if (modelValue instanceof File) {
      setFile(modelValue);
      setFileName(modelValue.name);
    } else if (typeof modelValue === 'string') {
      setFileName(modelValue);
    }
  }, [modelValue]);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const selectedFile = e.target.files?.[0] || null;
    setFile(selectedFile);
    setFileName(selectedFile?.name || null);
    onUpdateModelValue?.(selectedFile);
  };

  const handleButtonClick = () => {
    fileInputRef.current?.click();
  };

  return (
    <div className="s-file-input">
      <input
        ref={fileInputRef}
        type="file"
        className="d-none"
        onChange={handleChange}
        accept={accept}
        style={{ display: 'none' }}
      />
      <input
        type="text"
        value={fileName || ''}
        readOnly
        placeholder={placeholder}
        className="s-file-input__text"
        style={{
          border: errorMessages.length > 0 ? '1px solid red' : '1px solid #ccc',
          flex: 1,
        }}
      />
      {errorMessages.length > 0 && hideDetails !== true && (
        <div style={{ color: 'red', fontSize: '12px', marginTop: '4px' }}>
          {errorMessages[0]}
        </div>
      )}
      <SBtn height={36} variant="outlined" disabled={btnDisabled} onClick={handleButtonClick}>
        <SIcon name="file" size={16} className="mr-1" />
        {buttonText}
      </SBtn>
    </div>
  );
};

export default SFileInputBtn;
