// src/components/progress/SGlobalProgress.tsx
import React, { useEffect } from 'react';
import { createPortal } from 'react-dom';
import { SProgressCircular } from './SProgressCircular';
import './SGlobalProgress.scss';

interface SGlobalProgressProps {
  loadingMessage?: string;
  modelValue?: boolean;
  teleportId?: string;
}

export const SGlobalProgress: React.FC<SGlobalProgressProps> = ({
  loadingMessage = 'Check-loading',
  modelValue = false,
  teleportId = 'destination',
}) => {
  useEffect(() => {
    if (modelValue) {
      document.body.style.overflow = 'hidden';
    } else {
      document.body.style.overflow = '';
    }

    return () => {
      document.body.style.overflow = '';
    };
  }, [modelValue]);

  const overlayStyle: React.CSSProperties = {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'transparent',
    display: modelValue ? 'flex' : 'none',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 9999,
    marginTop: '68px',
    height: 'calc(100% - 68px)',
  };

  const content = (
    <div className="custom-overlay" style={overlayStyle}>
      <div className="s-loading">
        <div className="s-loading__message">{loadingMessage}</div>
        <div className="s-loading__spinner">
          <SProgressCircular />
        </div>
        <div className="s-loading__text">Please wait...</div>
      </div>
    </div>
  );

  const teleportElement = document.getElementById(teleportId);
  if (teleportElement) {
    return createPortal(content, teleportElement);
  }

  return content;
};

export default SGlobalProgress;

// src/components/progress/SGlobalProgress.vue
<!-- 전역 로딩 바 -->
<template>
  <teleport :to="`#${teleportId}`">
    <v-overlay
      :model-value="modelValue"
      class="custom-overlay"
      contained
      persistent
      no-click-animation
      scrim="transparent"
      z-index="9999"
      :offset="[0, 50]"
    >
      <div class="s-loading">
        <div class="s-loading__message">
          {{ loadingMessage }}
        </div>
        <div class="s-loading__spinner">
          <s-progress-circular />
        </div>
        <div class="s-loading__text">Please wait...</div>
      </div>
    </v-overlay>
  </teleport>
</template>

<script setup>
import { VOverlay } from 'vuetify/components'
import SProgressCircular from '@/components/progress/SProgressCircular.vue'

defineProps({
  loadingMessage: {
    type: String,
    default: 'Check-loading',
    description: '로딩창 메세지 값',
  },
  modelValue: {
    type: Boolean,
    default: false,
    description: '로딩 오픈 여부',
  },
  teleportId: {
    type: String,
    default: "destination",
    description: 'Teleport ID',
  }
})
</script>

<style lang="scss">
.s-loading {
  $this: 's-loading';
  position: fixed;
  background-color: white;
  width: 400px;
  height: 234px;
  border: 1px solid $s-default--gray-5;
  border-radius: 5px;
  transform: translate(-50%, -50%);
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 15px;

  .#{$this}__message {
    font-size: 18px;
    font-weight: bold;
    text-align: center;
    line-height: 26px;
  }
  .#{$this}__spinner {
    text-align: center;
  }
  .#{$this}__text {
    font-size: 14px;
    font-weight: 500;
    line-height: 22px;
    text-align: center;
  }
}

.custom-overlay {
  margin-top: 68px;
  height: calc(100% - 68px);
  align-items: center;
  justify-content: center;
}
</style>
