// src/components/progress/SProgressStages.tsx
import React, { useState } from 'react';
import './SProgressStages.scss';

interface Stage {
  title: string;
  status: 'completed' | 'in-progress' | 'pending' | 'delayed';
  subStages?: SubStage[];
}

interface SubStage {
  title: string;
  status: 'completed' | 'in-progress' | 'pending' | 'delayed';
  children?: SubStage[];
}

interface SProgressStagesProps {
  stages: Stage[];
}

export const SProgressStages: React.FC<SProgressStagesProps> = ({ stages = [] }) => {
  const [expanded, setExpanded] = useState<string[]>([]);

  const toggleSubStage = (key: string) => {
    setExpanded(prev => {
      const index = prev.indexOf(key);
      if (index === -1) {
        return [...prev, key];
      } else {
        return prev.filter(k => k !== key);
      }
    });
  };

  const getStageHeaderClass = (stage: Stage) => {
    return {
      'stage-header--completed': stage.status === 'completed',
      'stage-header--in-progress': stage.status === 'in-progress',
      'stage-header--pending': stage.status === 'pending',
      'stage-header--delayed': stage.status === 'delayed',
    };
  };

  const getStageStatusClass = (stage: SubStage) => {
    return {
      'sub-stage-item--completed': stage.status === 'completed',
      'sub-stage-item--in-progress': stage.status === 'in-progress',
      'sub-stage-item--pending': stage.status === 'pending',
      'sub-stage-item--delayed': stage.status === 'delayed',
    };
  };

  const getStatusIcon = (status: string) => {
    switch (status) {
      case 'completed':
        return 'mdi-check-circle';
      case 'in-progress':
        return 'mdi-progress-clock';
      default:
        return 'mdi-circle-outline';
    }
  };

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'completed':
        return '#00BA88';
      case 'in-progress':
        return '#1297F2';
      default:
        return '#9E9E9E';
    }
  };

  const getTextColor = (status: string) => {
    switch (status) {
      case 'completed':
        return '#00BA88';
      case 'in-progress':
        return '#1297F2';
      default:
        return '#6C6C6C';
    }
  };

  return (
    <div className="progress-stages">
      {stages.map((stage, stageIndex) => (
        <div key={stageIndex} className="stage-item">
          <div className={`stage-header ${Object.entries(getStageHeaderClass(stage))
            .filter(([_, value]) => value)
            .map(([key]) => key)
            .join(' ')}`}>
            <div className="d-flex align-center">
              <i
                className={`mdi ${getStatusIcon(stage.status)} mr-2`}
                style={{ color: getStatusColor(stage.status), fontSize: '20px' }}
              />
              <span className="stage-title">{stage.title}</span>
            </div>
          </div>

          <div className="sub-stages">
            {(stage.subStages || []).map((subStage, subStageIndex) => {
              const key = `${stageIndex}-${subStageIndex}`;
              const isExpanded = expanded.includes(key);

              return (
                <div
                  key={key}
                  className={`sub-stage-item ${Object.entries(getStageStatusClass(subStage))
                    .filter(([_, value]) => value)
                    .map(([key]) => key)
                    .join(' ')}`}
                >
                  <div className="d-flex align-center justify-space-between">
                    <span style={{ color: getTextColor(subStage.status) }}>
                      {subStage.title}
                    </span>
                    {subStage.children?.length && (
                      <i
                        className={`mdi ${isExpanded ? 'mdi-chevron-up' : 'mdi-chevron-down'}`}
                        style={{ cursor: 'pointer', fontSize: '20px' }}
                        onClick={() => toggleSubStage(key)}
                      />
                    )}
                  </div>

                  {isExpanded && subStage.children?.length && (
                    <div className="sub-stage-children">
                      {subStage.children.map((child, index) => (
                        <div
                          key={index}
                          className={`sub-stage-child ${Object.entries(getStageStatusClass(child))
                            .filter(([_, value]) => value)
                            .map(([key]) => key)
                            .join(' ')}`}
                        >
                          {child.title}
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        </div>
      ))}
    </div>
  );
};

export default SProgressStages;

// src/components/progress/SProgressStages.vue
<template>
  <div class="progress-stages">
    <div v-for="(stage, stageIndex) in stages" :key="stageIndex" class="stage-item">
      <div class="stage-header" :class="getStageHeaderClass(stage)">
        <div class="d-flex align-center">
          <v-icon :icon="getStatusIcon(stage.status)" :color="getStatusColor(stage.status)" size="small" class="mr-2" />
          <span class="stage-title">{{ stage.title }}</span>
        </div>
      </div>

      <div class="sub-stages">
        <div
          v-for="(subStage, subStageIndex) in stage.subStages"
          :key="`${stageIndex}-${subStageIndex}`"
          class="sub-stage-item"
          :class="getStageStatusClass(subStage)"
        >
          <div class="d-flex align-center justify-space-between">
            <span :style="{ color: getTextColor(subStage.status) }">
              {{ subStage.title }}
            </span>
            <v-icon
              v-if="subStage.children?.length"
              :icon="expanded.includes(`${stageIndex}-${subStageIndex}`) ? 'mdi-chevron-up' : 'mdi-chevron-down'"
              size="small"
              @click.stop="toggleSubStage(`${stageIndex}-${subStageIndex}`)"
            />
          </div>

          <v-expand-transition>
            <div v-if="expanded.includes(`${stageIndex}-${subStageIndex}`) && subStage.children?.length" class="sub-stage-children">
              <div
                v-for="(child, index) in subStage.children"
                :key="index"
                class="sub-stage-child"
                :class="getStageStatusClass(child)"
              >
                {{ child.title }}
              </div>
            </div>
          </v-expand-transition>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'

const { stages } = defineProps({
  stages: {
    type: Array,
    required: true,
  },
})

const expanded = ref([])

const toggleSubStage = key => {
  const index = expanded.value.indexOf(key)
  if (index === -1) {
    expanded.value.push(key)
  } else {
    expanded.value.splice(index, 1)
  }
}

const getStageHeaderClass = stage => {
  return {
    'stage-header--completed': stage.status === 'completed',
    'stage-header--in-progress': stage.status === 'in-progress',
    'stage-header--pending': stage.status === 'pending',
    'stage-header--delayed': stage.status === 'delayed',
  }
}

const getStageStatusClass = stage => {
  return {
    'sub-stage-item--completed': stage.status === 'completed',
    'sub-stage-item--in-progress': stage.status === 'in-progress',
    'sub-stage-item--pending': stage.status === 'pending',
    'sub-stage-item--delayed': stage.status === 'delayed',
  }
}

const getStatusIcon = status => {
  switch (status) {
    case 'completed':
      return 'mdi-check-circle'
    case 'in-progress':
      return 'mdi-progress-clock'
    default:
      return 'mdi-circle-outline'
  }
}

const getStatusColor = status => {
  switch (status) {
    case 'completed':
      return 'success'
    case 'in-progress':
      return 'primary'
    default:
      return 'grey'
  }
}

const getTextColor = status => {
  switch (status) {
    case 'completed':
      return '#00BA88' // success dark
    case 'in-progress':
      return '#1297F2' // primary dark
    default:
      return '#6C6C6C' // grey darken-1
  }
}
</script>

<style lang="scss" scoped>
.progress-stages {
  display: grid;
  grid-template-columns: repeat(6, 1fr);
  gap: 20px;
  margin-top: 20px;

  .stage-item {
    border: 1px solid $s-default--gray-5;
    border-radius: 4px;
    overflow: hidden;

    .stage-header {
      padding: 12px;
      background-color: $s-default--gray-1;
      display: flex;
      justify-content: space-between;
      align-items: center;
      cursor: default;

      &.stage-header--completed {
        background-color: rgba($s-btn--green-1, 0.1);
      }

      &.stage-header--in-progress {
        background-color: rgba($s-btn--blue-1, 0.1);
      }

      &.stage-header--pending {
        background-color: rgba($s-default--gray-8, 0.1);
      }

      &.stage-header--delayed {
        background-color: rgba($s-btn--red-1, 0.1);
      }
    }

    .sub-stages {
      .sub-stage-item {
        padding: 8px 12px;
        border-top: 1px solid #e0e0e0;
        font-size: 0.9rem;
        cursor: default;

        &:has(.mdi-chevron-up, .mdi-chevron-down) {
          cursor: pointer;
        }

        &.sub-stage-item--completed {
          background-color: rgba($s-btn--green-1, 0.05);
        }

        &.sub-stage-item--in-progress {
          background-color: rgba($s-btn--blue-1, 0.05);
        }

        &.sub-stage-item--pending {
          background-color: rgba($s-default--gray-8, 0.05);
        }

        &.sub-stage-item--delayed {
          background-color: rgba($s-btn--red-1, 0.05);
        }

        .sub-stage-children {
          margin-left: 20px;
          margin-top: 8px;

          .sub-stage-child {
            padding: 4px 0;
            font-size: 0.9em;

            &.sub-stage-item--completed {
              color: $s-btn--green-1; // success dark
            }

            &.sub-stage-item--in-progress {
              color: $s-btn--blue-1; // primary dark
            }

            &.sub-stage-item--pending {
              color: $s-default--gray-8; // grey darken-1
            }

            &.sub-stage-item--delayed {
              color: $s-btn--red-1; // error dark
            }
          }
        }
      }
    }
  }
}
</style>
