// src/components/modal/SConfirm.vue
<template>
  <teleport :to="`#${teleportId}`">
    <v-dialog
      class="s-confirm-modal"
      width="446"
      persistent
      :model-value="modelValue"
      @update:model-value="updateModelValue"
    >
      <v-card modal-height="210">
        <v-card-text class="s-confirm-modal__text">
          {{ contents }}
        </v-card-text>
        <v-card-actions class="button-wrapper">
          <s-btn variant="elevated" color="blue" @click.stop="onConfirm">
            <s-icon name="check" :size="16" class="mr-1" />
            {{ confirmButtonText }}
          </s-btn>
          <s-btn variant="outlined" color="blue" @click="onCancel" v-if="!noCancel">
            <s-icon name="close" :size="16" class="mr-1" />
            {{ cancelButtonText }}
          </s-btn>
        </v-card-actions>
      </v-card>
    </v-dialog>
  </teleport>
</template>

<script setup>
import { SBtn, SIcon } from '@/components'
const emits = defineEmits(['update:model-value', 'click:confirm', 'click:cancel'])

defineProps({
  contents: {
    type: String,
    default: '',
    description: '컨펌창 내용',
  },
  modelValue: {
    type: Boolean,
    default: false,
    description: '컨펌창 오픈 여부',
  },
  teleportId: {
    type: String,
    default: 'destination',
    description: 'Teleport ID',
  },
  confirmButtonText: {
    type: String,
    default: '확인',
    description: '확인 버튼의 텍스트',
  },
  cancelButtonText: {
    type: String,
    default: '취소',
    description: '취소 버튼의 텍스트',
  },
  noCancel: {
    type: Boolean,
    default: false,
    description: '취소 버튼의 텍스트',
  }
})

const updateModelValue = value => {
  emits('update:model-value', value)
}

const onConfirm = () => emits('click:confirm')
const onCancel = () => emits('click:cancel', false)
</script>

<style lang="scss" scoped>
.s-confirm-modal {
  margin: 0 auto;
  .s-confirm-modal__text {
    text-align: center;
    display: flex;
    align-items: center;
    justify-content: center;
    min-height: 130px;
    white-space: pre-line;
    word-break: break-word;
  }

  .button-wrapper {
    width: 100%;
    display: flex;
    justify-content: center !important;
    align-items: center;
    padding: 0 0 27px;

    > button {
      min-width: 110px;
      height: 36px;
    }
  }

  :deep(.v-dialog) {
    .v-overlay__content > .v-card {
      border-radius: 8px;
    }
  }
}
</style>

// src/components/modal/SConfirm.tsx
import React, { useEffect } from 'react';
import { createPortal } from 'react-dom';
import { SBtn } from '../button/SBtn';
import { SIcon } from '../images/SIcon';
import './SConfirm.scss';

interface SConfirmProps {
  contents?: string;
  modelValue?: boolean;
  teleportId?: string;
  confirmButtonText?: string;
  cancelButtonText?: string;
  noCancel?: boolean;
  onUpdateModelValue?: (value: boolean) => void;
  onClickConfirm?: () => void;
  onClickCancel?: () => void;
}

export const SConfirm: React.FC<SConfirmProps> = ({
  contents = '',
  modelValue = false,
  teleportId = 'destination',
  confirmButtonText = '확인',
  cancelButtonText = '취소',
  noCancel = false,
  onUpdateModelValue,
  onClickConfirm,
  onClickCancel,
}) => {
  useEffect(() => {
    if (modelValue) {
      document.body.style.overflow = 'hidden';
    } else {
      document.body.style.overflow = '';
    }

    return () => {
      document.body.style.overflow = '';
    };
  }, [modelValue]);

  const updateModelValue = (value: boolean) => {
    onUpdateModelValue?.(value);
  };

  const onConfirm = () => {
    onClickConfirm?.();
    updateModelValue(false);
  };

  const onCancel = () => {
    onClickCancel?.();
    updateModelValue(false);
  };

  if (!modelValue) {
    return null;
  }

  const content = (
    <div
      className="s-confirm-modal"
      onClick={(e) => {
        if (e.target === e.currentTarget) {
          updateModelValue(false);
        }
      }}
    >
      <div onClick={(e) => e.stopPropagation()}>
        <div className="s-confirm-modal__text">
          {contents}
        </div>
        <div className="button-wrapper">
          <SBtn variant="elevated" color="blue" onClick={onConfirm}>
            <SIcon name="check" size={16} className="mr-1" />
            {confirmButtonText}
          </SBtn>
          {!noCancel && (
            <SBtn variant="outlined" color="blue" onClick={onCancel}>
              <SIcon name="close" size={16} className="mr-1" />
              {cancelButtonText}
            </SBtn>
          )}
        </div>
      </div>
    </div>
  );

  const teleportElement = document.getElementById(teleportId);
  if (teleportElement) {
    return createPortal(content, teleportElement);
  }

  return content;
};

export default SConfirm;
