// src/components/modal/SModal.tsx
import React, { useEffect, useMemo } from 'react';
import { createPortal } from 'react-dom';
import { SBtn } from '../button/SBtn';
import { SIcon } from '../images/SIcon';
import './SModal.scss';

interface SModalProps {
  title?: string;
  className?: string | { [key: string]: boolean };
  modalWidth?: string;
  modalHeight?: string;
  modelValue?: boolean;
  isWhite?: boolean;
  popupCardClass?: string;
  hideHeader?: boolean;
  teleportId?: string;
  size?: 'x-small' | 'small' | 'medium' | 'large' | 'x-large';
  languageCode?: 'ko' | 'en';
  mode?: 'new' | 'detail' | 'update' | null;
  changeMode?: (mode: 'new' | 'detail' | 'update') => void;
  onClose?: () => void;
  onCancel?: () => void;
  onSave?: () => void;
  onEdit?: () => void;
  onUpdate?: () => void;
  hideSaveButton?: boolean;
  hideEditButton?: boolean;
  hideCloseButton?: boolean;
  hideCancelButton?: boolean;
  onUpdateModelValue?: (value: boolean) => void;
  onFetch?: () => void;
  children?: React.ReactNode;
  buttons?: React.ReactNode;
  headerBtnAppend?: React.ReactNode;
  footer?: React.ReactNode;
}

export const SModal: React.FC<SModalProps> = ({
  title = '',
  className = '',
  modalWidth = '',
  modalHeight = '',
  modelValue = false,
  isWhite = false,
  popupCardClass = '',
  hideHeader = false,
  teleportId = 'destination',
  size = 'medium',
  languageCode = 'ko',
  mode = null,
  changeMode,
  onClose,
  onCancel,
  onSave,
  onEdit,
  onUpdate,
  hideSaveButton = false,
  hideEditButton = false,
  hideCloseButton = false,
  hideCancelButton = false,
  onUpdateModelValue,
  onFetch,
  children,
  buttons,
  headerBtnAppend,
  footer,
}) => {
  const buttonText = {
    ko: { save: '저장', update: '수정', close: '닫기', cancel: '취소' },
    en: { save: 'Save', update: 'Update', close: 'Close', cancel: 'Cancel' },
  };

  const isNewMode = mode === 'new';
  const isDetailMode = mode === 'detail';
  const isUpdateMode = mode === 'update';
  const buttonLabels = buttonText[languageCode];

  const modalClass = useMemo(() => {
    const classes = ['s-modal'];
    if (typeof className === 'string') {
      classes.push(className);
    } else if (typeof className === 'object') {
      classes.push(...Object.keys(className).filter(key => className[key]));
    }
    return classes.join(' ');
  }, [className]);

  const modalDataAttributes = {
    'data-size': size,
  };

  const controlBodyScroll = (shouldLock: boolean) => {
    if (shouldLock) {
      document.body.style.overflow = 'hidden';
      // 스크롤바 너비 계산
      const scrollbarWidth = window.innerWidth - document.documentElement.clientWidth;
      document.body.style.paddingRight = `${scrollbarWidth}px`;
    } else {
      document.body.style.overflow = '';
      document.body.style.paddingRight = '';
    }
  };

  useEffect(() => {
    if (modelValue) {
      onFetch?.();
      controlBodyScroll(true);
    } else {
      controlBodyScroll(false);
    }

    return () => {
      controlBodyScroll(false);
    };
  }, [modelValue, onFetch]);

  const closeModal = () => {
    onUpdateModelValue?.(false);
  };

  const onClickCloseModal = () => {
    closeModal();
  };

  const onClickCancel = () => {
    if (!changeMode) {
      throw Error('Not found changeMode');
    }

    onCancel?.();
    if (mode === 'update') {
      changeMode('detail');
    } else {
      closeModal();
    }
  };

  const onClickClose = () => {
    onClose?.();
    closeModal();
  };

  const onClickUpdate = () => {
    onUpdate?.();
  };

  const onClickEdit = () => {
    if (mode === 'detail') {
      changeMode?.('update');
    }
    onEdit?.();
  };

  const modalStyle: React.CSSProperties = {
    display: modelValue ? 'flex' : 'none',
  };

  const cardStyle: React.CSSProperties = {
    width: modalWidth || undefined,
    height: modalHeight || undefined,
    minHeight: modalHeight || undefined,
  };

  if (!modelValue) {
    return null;
  }

  const content = (
    <div
      className={modalClass}
      style={modalStyle}
      {...modalDataAttributes}
      onClick={(e) => {
        if (e.target === e.currentTarget) {
          closeModal();
        }
      }}
    >
      <div className={`s-modal__card ${popupCardClass}`} style={cardStyle} onClick={(e) => e.stopPropagation()}>
        {!hideHeader && (
          <div className={`s-modal__title ${isWhite ? 's-modal__title--light' : 's-modal__title--dark'}`}>
            <span>{title}</span>
            <div className="button-wrapper">
              {headerBtnAppend}
              <i
                className={`mdi mdi-close`}
                style={{ color: isWhite ? '#1A3350' : '#fff', cursor: 'pointer' }}
                onClick={onClickCloseModal}
              />
            </div>
          </div>
        )}

        <div className="s-modal__content-wrapper">
          <div className="s-modal__content">
            {children}
          </div>
        </div>

        <div className="s-modal__footer">
          {footer || buttons || (
            <>
              {(isNewMode || (!hideEditButton && isDetailMode) || isUpdateMode) && (
                <div className="s-modal__footer__positive">
                  {!hideSaveButton && isNewMode && (
                    <SBtn onClick={onSave}>
                      <SIcon name="save" size={16} className="mr-1" />
                      {buttonLabels.save}
                    </SBtn>
                  )}
                  {!hideEditButton && isDetailMode && (
                    <SBtn onClick={onClickEdit}>
                      <SIcon name="edit" size={16} className="mr-1" />
                      {buttonLabels.update}
                    </SBtn>
                  )}
                  {!hideSaveButton && isUpdateMode && (
                    <SBtn onClick={onClickUpdate}>
                      <SIcon name="edit" size={16} className="mr-1" />
                      {buttonLabels.save}
                    </SBtn>
                  )}
                </div>
              )}

              {((!hideCloseButton && isDetailMode) || (!hideCancelButton && (isNewMode || isUpdateMode))) && (
                <>
                  {!hideCloseButton && isDetailMode && (
                    <SBtn variant="outlined" onClick={onClickClose}>
                      <SIcon name="close" size={16} className="mr-1" />
                      {buttonLabels.close}
                    </SBtn>
                  )}
                  {!hideCancelButton && (isNewMode || isUpdateMode) && (
                    <SBtn variant="outlined" onClick={onClickCancel}>
                      <SIcon name="close" size={16} className="mr-1" />
                      {buttonLabels.cancel}
                    </SBtn>
                  )}
                </>
              )}
            </>
          )}
        </div>
      </div>
    </div>
  );

  const teleportElement = document.getElementById(teleportId);
  if (teleportElement) {
    return createPortal(content, teleportElement);
  }

  return content;
};

export default SModal;

// src/components/modal/SModal.vue
<template>
  <teleport :to="`#${teleportId}`">
    <v-dialog :model-value="modelValue" :width="modalWidth" scroll-strategy="block" :class="ModalClass"
        :size="size" persistent scrim @update:model-value="val => { emits('update:model-value', val) }">

      <template #activator="{ props }">
        <slot name="buttons" v-on="props" />
      </template>

      <v-card :class="popupCardClass" :height="modalHeight" :min-height="modalHeight" no-line>
        <template v-if="!hideHeader" #prepend>
          <div class="s-modal__title" :class="{ 's-modal__title--light': isWhite, 's-modal__title--dark': !isWhite }">
            <span>{{ title }}</span>
            <div class="button-wrapper">
              <slot name="header-btn-append" />
              <v-icon icon="mdi-close" :color="isWhite ? '#1A3350' : '#fff'" @click="onClickCloseModal" />
            </div>
          </div>
        </template>

        <template #item>
          <div class="s-modal__content-wrapper">
            <div class="s-modal__content">
              <slot name="default" />
            </div>
          </div>
        </template>

        <template #append>
          <div class="s-modal__footer">
            <slot name="footer" />

            <div v-if="isNewMode || (!hideEditButton && isDetailMode) || isUpdateMode"
                 class="s-modal__footer__positive">
              <SBtn v-if="!hideSaveButton && isNewMode" @click="onSave">
                <s-icon name="save" v-bind="commonIconProps" />{{ buttonLabels.save }}
              </SBtn>
              <SBtn v-if="!hideEditButton && isDetailMode" @click="onClickEdit">
                <s-icon name="edit" v-bind="commonIconProps" />{{ buttonLabels.update }}
              </SBtn>
              <SBtn v-if="!hideSaveButton && isUpdateMode" @click="onClickUpdate">
                <s-icon name="edit" v-bind="commonIconProps" />{{ buttonLabels.save }}
              </SBtn>
            </div>

            <div v-if="(!hideCloseButton && isDetailMode) || (!hideCancelButton && (isNewMode || isUpdateMode))">
              <SBtn v-if="!hideCloseButton && isDetailMode" variant="outlined" @click="onClickClose">
                <s-icon name="close" :size="16" class="mr-1"/>{{ buttonLabels.close }}
              </SBtn>
              <SBtn v-if="!hideCancelButton && (isNewMode || isUpdateMode)" variant="outlined" @click="onClickCancel">
                <s-icon name="close" :size="16" class="mr-1"/>{{ buttonLabels.cancel }}
              </SBtn>
            </div>

          </div>
        </template>
      </v-card>
    </v-dialog>
  </teleport>
</template>
<script setup>
import { computed, onBeforeUnmount, useAttrs, watch } from 'vue'
import SBtn from '@/components/button/SBtn.vue'

const commonIconProps = { size: "16", class: "mr-1" }
const buttonText = {
  'ko': { save: '저장', update: '수정', close: '닫기', cancel: '취소' },
  'en': { save: 'Save', update: 'Update', close: 'Close', cancel: 'Cancel' },
}

// region [Defines]
const emits = defineEmits(['update:model-value', 'on-fetch'])
const attrs = useAttrs()

const props = defineProps({
  title: { type: String, default: '', description: '모달 헤더 이름' },
  className: { type: [Object, String], default: '', description: '클래스 명' },
  modalWidth: { type: String, default: '', description: '모달 넓이' },
  modalHeight: { type: String, default: '', description: '모달 높이' },
  modelValue: { type: Boolean, default: false, description: '모달 오픈 여부' },
  isWhite: { type: Boolean, default: false, description: '모달 헤드 색깔 여부' },
  popupCardClass: { type: String, default: '', description: 'card의 개별 클래스네임' },
  hideHeader: { type: Boolean, default: false, description: '헤더 유무' },
  teleportId: { type: String, default: 'destination', description: 'Teleport ID' },
  size: { type: String, default: 'medium', description: 'modal size x-small, small, medium, large, x-large' },
  languageCode: { type: String, default: 'ko', description: 'ko, en' },
  mode: { type: String, default: null, description: "new | detail | update" },
  changeMode: { type: Function, default: () => {} },
  onClose: { type: Function, default: null, description: '닫기 버튼 눌렀을 때 함수' },
  onCancel: { type: Function, default: null, description: '취소 버튼 눌렀을 때 함수' },
  onSave: { type: Function, default: null, description: 'new 모드에서 저장 버튼 눌렀을 때 함수' },
  onEdit: { type: Function, default: null, description: 'detail 모드에서 수정 버튼 눌렀을 때 함수' },
  onUpdate: { type: Function, default: null, description: 'update 모드에서 저장 버튼 눌렀을 때 함수' },
  hideSaveButton: { type: Boolean, default: false, description: 'new 모드에서 저장 버튼 숨기기' },
  hideEditButton: { type: Boolean, default: false, description: 'detail 모드에서 수정 버튼 숨기기' },
  hideCloseButton: { type: Boolean, default: false, description: 'detail 모드에서 닫기 버튼 숨기기' },
  hideCancelButton: { type: Boolean, default: false, description: 'new, update 모드에서 취소 버튼 숨기기' },
})
// endregion

// region [Computed]
const ModalClass = computed(() => ['s-modal', props.className].join(' '))

const isNewMode = computed(() => props.mode === 'new')
const isDetailMode = computed(() => props.mode === 'detail')
const isUpdateMode = computed(() => props.mode === 'update')
const buttonLabels = computed(() => buttonText[props.languageCode])
// endregion


// region [Privates]
const initializeModal = (isOpen) => {
  if (isOpen) { emits('on-fetch') }
  controlBodyScroll(isOpen)
}

const controlBodyScroll = (shouldLock) => {
  if (shouldLock) {
    document.body.style.overflow = 'hidden'
    document.body.style.paddingRight = 'var(--v-scrollbar-offset)'
  } else {
    document.body.style.overflow = ''
    document.body.style.paddingRight = ''
  }
}

const closeModal = () => { emits('update:model-value', false) }
// endregion


// region [Events]
const onClickCloseModal = closeModal

const onClickCancel = () => {
  if (!props?.changeMode) {
    throw Error('Not found changeMode')
  }

  props?.onCancel?.()
  if (props.mode === 'update') {
    props.changeMode?.('detail') // update 모드인 경우 자동으로 detail 모드 전환
  } else {
    closeModal() // new 모드인 경우 모달 닫기
  }
}

const onClickClose = () => {
  props?.onClose?.()
  closeModal() // 자동으로 모달 닫기 함수 실행
}

const onClickUpdate = () => {
  props?.onUpdate?.()
}

const onClickEdit = () => {
  if (props.mode === 'detail') {
    props.changeMode?.('update') // detail 모드인 경우 자동으로 update 모드 전환
  }
}
// endregion


// region [Life Cycles]
watch(() => props.modelValue, initializeModal)
onBeforeUnmount(() => { controlBodyScroll(false) })
// endregion
</script>

<style lang="scss" scoped>
@import url('./SModal.scss');
</style>
