// src/components/accordion/SAccordionMenu.tsx
import React, { useState, useRef } from 'react';
import './SAccordionMenu.scss';

interface SAccordionMenuProps {
  title: string;
  titleBold?: boolean;
  children?: React.ReactNode;
}

export const SAccordionMenu: React.FC<SAccordionMenuProps> = ({
  title,
  titleBold = false,
  children,
}) => {
  const [isActive, setIsActive] = useState(false);
  const [accordionHeight, setAccordionHeight] = useState('0px');
  const accordionRef = useRef<HTMLDivElement>(null);

  const toggleAccordion = () => {
    if (!accordionRef.current) return;

    if (isActive) {
      setAccordionHeight(`${accordionRef.current.scrollHeight}px`);
      requestAnimationFrame(() => {
        setAccordionHeight('0px');
        setIsActive(false);
      });
    } else {
      setAccordionHeight(`${accordionRef.current.scrollHeight}px`);
      setIsActive(true);
    }
  };

  const onTransitionEnd = () => {
    if (isActive) {
      setAccordionHeight('auto');
    }
  };

  return (
    <div className="s-accordion-wrapper">
      <div className={`title ${titleBold ? 'title-bold' : ''}`}>
        {title}
        <i
          className={`mdi ${isActive ? 'mdi-chevron-down' : 'mdi-chevron-right'} s-accordion-icon`}
          onClick={toggleAccordion}
        />
      </div>
      <div
        ref={accordionRef}
        className="s-accordion-contents"
        style={{ height: accordionHeight }}
        onTransitionEnd={onTransitionEnd}
      >
        {children}
      </div>
    </div>
  );
};

export default SAccordionMenu;

// src/components/accordion/SAccordionMenu.vue
<template>
  <div class="s-accordion-wrapper">
    <div class="title" :class="{ 'title-bold': titleBold }">
      {{ title }}
      <v-icon class="float-right" :style="{ top: '10px' }" :icon="isActive ? 'mdi-chevron-down' : 'mdi-chevron-right'" @click="toggleAccordion" />
    </div>
    <div
        ref="accordion"
        class="s-accordion-contents"
        :style="{ height: accordionHeight }"
        @transitionend="onTransitionEnd"
    >
      <slot />
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'

defineProps({
  title: {
    type: String,
    required: true,
  },
  titleBold: {
    type: Boolean,
    default: false,
  },
})

const accordion = ref(null)
const isActive = ref(false)
const accordionHeight = ref('0px')

const toggleAccordion = () => {
  if (isActive.value) {
    accordionHeight.value = `${accordion.value.scrollHeight}px` // 현재 높이 설정
    requestAnimationFrame(() => {
      accordionHeight.value = '0px' // 닫히는 애니메이션
      isActive.value = false
    })
  } else {
    accordionHeight.value = `${accordion.value.scrollHeight}px` // 열리는 애니메이션
    isActive.value = true
  }
}

const onTransitionEnd = () => {
  if (isActive.value) {
    accordionHeight.value = 'auto' // 열린 상태에서 auto로 설정
  }
}
</script>

<style lang="scss" scoped>
.s-accordion-wrapper {
  font-size: 18px;
  line-height: 50px;
  overflow: hidden;
}

.s-accordion-contents {
  height: 0;
  transition: height 0.5s;
}

.title-bold {
  font-weight: bold;
}
</style>
